- hosts: all
  gather_facts: no
  vars:
    ansible_user: admin  # Replace with your actual username if different
  tasks:
    - name: Change password via Expect script
      delegate_to: localhost
      connection: local
      vars:
        host: "{{ inventory_hostname }}"
        user: "{{ ansible_user }}"
        initial_pass: "{{ initial_password }}"
        new_pass: "{{ new_password }}"
      shell: "./change_password.exp {{ host }} {{ user }} '{{ initial_pass }}' '{{ new_pass }}'"
      register: change_password_result
      failed_when: change_password_result.rc != 0